# Generated by Django 4.2.6 on 2023-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=900)),
                ('short_url', models.CharField(max_length=90)),
                ('time_date_created', models.DateTimeField()),
            ],
        ),
    ]
